name: CI

on:
  push:
  #  branches: [ master ]
  pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install jshint uglify-js copyfiles mkdirp
    - run: npm run lint
    - run: npm run deploy
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  pages:
    #if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Publish to github pages
        run: |
          rm -rf *
          mv build/* .
          rm -rf build
          touch .nojekyll # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
          git config user.name gh-actions
          git config user.email gh-actions@github.com
          git add .
          git commit --reset-author --amend -m "Autodeploy"
          git push --force origin gh-pages
