name: CI

on:
  push:
  #  branches: [ master ]
  pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install jshint uglify-js copyfiles mkdirp
    - run: npm run lint
    - run: npm run deploy
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
